name: test
on: [push]
jobs:
  lint:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1

  unit:
    name: Unit tests Lua
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua_version: ["5.1", "5.2", "5.3", "5.4"]

    container:
      image: alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apk add --update lua${{ matrix.lua_version }} lua${{ matrix.lua_version }}-busted
      - name: Run tests
        run: |
          busted-${{ matrix.lua_version }}
